import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import '../styles/globals.css';

const outfit = Archivo({ 
  subsets: ["latin"],
  display: 'swap',
  weight: ['100', '200', '300', '400','600', '700', '800', '900'],
  // adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "Prayer Chain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>{children}</body>
    </html>
  );
}
